//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessages
    {
        public int id { get; set; }
        public int sender_id { get; set; }
        public int reciever_id { get; set; }
        public string Time { get; set; }
        public string Message { get; set; }
        public Nullable<int> read { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
