//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncryptorEngine
    {
        public int id { get; set; }
        public int user_Id { get; set; }
        public string encrypted_name { get; set; }
        public string encrypted_password { get; set; }
        public string encrypted_IV { get; set; }
        public string decrypted_filePath { get; set; }
        public string decrypted_name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
