//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordManager
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string account_website { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
