//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POs3de1PIIEntities : DbContext
    {
        public POs3de1PIIEntities()
            : base("name=POs3de1PIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Chat_Info> Chat_Info { get; set; }
        public virtual DbSet<EncryptorEngine> EncryptorEngines { get; set; }
        public virtual DbSet<Operation_Ids> Operation_Ids { get; set; }
        public virtual DbSet<Operation_Info> Operation_Info { get; set; }
        public virtual DbSet<Operation_Types> Operation_Types { get; set; }
        public virtual DbSet<UserPasswordManager> UserPasswordManagers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
